### ISSUE TITLE
underscore between Fig and Gen the FigGenForNearOptPaper?

### ISSUE THREAD

**Issue by amabdallah** [dzeke/Blended-Near-Optimal-Tools#1]
At point (d) in the instructions on the ReadMe homepage, when I execute this the function FigGenForNearOptPaper, Matlab suggests to me a slightly different below which includes an underscore between Fig and Gen. Is that correct?  
Then when I hit enter to the suggested function, Figure 1 and 2 pop up just fine but these error lines below appear which obviously prevent the rest of Figures from showing up. I'm using Matlab R2015a. Any suggestions to fix these errors? Thanks  

> > FigGenForNearOptPaper
> > Undefined function or variable 'FigGenForNearOptPaper'.

Did you mean:

> > Fig_GenForNearOptPaper

Error using rgdx
File 'WQNE_outG6.gdx' not found!

Error in LoadEchoGamsResultsMGAComp (line 181)
    vScalarVals(i) = cell2mat(PrintGamsSo(rgdx(GDXFile,sScalar)));

Error in Fig_GenForNearOptPaper (line 108)
[mResult nObjs vParams] = LoadEchoGamsResultsMGAComp('WQNE_outG6.gdx',3,2500,0,[2 0 50]);

**Comment by dzeke** [comment]
Yes, the underscore is omitted in the documentation. Now fixed.

To fix the error related to rgdx, first switch the Matlab directory to the directory where you downloaded the file WQNE_outG6.gdx: /4-EchoReservoirApplication. Then rerun the script.

David
